### ISSUE TITLE
README issues

### ISSUE THREAD

**Issue by Sigfried** [chrisroederucdenver/CCDA_OMOP_by_Python#36] opened 2024-08-07 12:33 UTC
- [ ] [Tools detail](https://github.com/chrisroederucdenver/CCDA_OMOP_by_Python/blob/f6287b73350e54d1458d2455a233d955e277180b/README.md?plain=1#L14-L23)
  - These are mostly in obs_tools now. For ongoing documentation, do we want this here?
- [ ] [Try and run basic_example.py](https://github.com/chrisroederucdenver/CCDA_OMOP_by_Python/blob/f6287b73350e54d1458d2455a233d955e277180b/README.md?plain=1#L36)
```
    File "/Users/sigfried/git-repos/CLAD/CCDA_OMOP_by_Python/prototype/basic_example.py", line 75
        resources/170.314b2_AmbulatoryToC.xml
                        ^
    SyntaxError: invalid decimal literal
```
- [ ] [.github/workflows. For now there is one file, just_run.yml](https://github.com/chrisroederucdenver/CCDA_OMOP_by_Python/blob/f6287b73350e54d1458d2455a233d955e277180b/README.md?plain=1#L70)
  - Not there anymore.

**Comment by chrisroederucdenver** [comment] 2024-08-07 12:59
closed as duplicate of #13

**Closed by chrisroederucdenver** 2024-08-07 12:59 UTC
